# Generated by Django 2.0.6 on 2018-08-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Hobby', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
            ],
        ),
    ]
